### ISSUE TITLE
an idear for your addon

### ISSUE THREAD

**Issue by Goten87** [elvador/TransmogCleanup#14]
well u can sell items we alrdy learned
what if we in the option have a way to set names to sent items to in mail that we have not yet learned
so when i farm on my druid and i get green plate i dont have yet
i can sent it to my warrior in 1 click same with all other types
just make a list with all types of gear and wappons we can fil in a name to it and when we press the sent butten it will sent all the gear to the char that can learn it

**Comment by eTzmNcbkrng** [comment]
This AddOn does what you want.
https://github.com/eTzmNcbkrng/WardrobeTools

It places two buttons in you mailbox. One is to configure it, one is to send all configured items.
