### ISSUE TITLE
8.0 Update

### ISSUE THREAD

**Issue by Gorthezar** [elvador/TransmogCleanup#21]
Please. This is my last addon not updated for BfA.

**Comment by elvador** [comment]
The addons works fine with the latest alpha version, you'll just need to check "Load outdated addons".

**Comment by sean-m-sullivan** [comment]
Does not work for 8.1, I haven't checked the code to find out what was wrong

**Comment by elvador** [comment]
Are you getting any errors? Install BugGrabber and BugSack if you don't have them already.
