### ISSUE TITLE
Please Update for Shadowlands pre-patch.

### ISSUE THREAD

**Issue by goodwin88** [elvador/TransmogCleanup#22]
I love this addon so much, please and thank you!

**Comment by elvador** [comment]
I updated it yesterday- any issues you're running into?
https://www.curseforge.com/wow/addons/transmogcleanup/files

**Comment by goodwin88** [comment]
Maybe I am misunderstanding the most basic settings then, I'm sorry.  But I have a bag full of stuff, then I go to vendor and open the sell transmog window and nothing is listed, nothing happens, it doesn't work.  So I still have to sell thing individually by hand.

**Comment by elvador** [comment]
Are you sure you're on the latest version? Can you post a ingame screenshot of the window?

**Comment by goodwin88** [comment]
Here, specifically:

- The checkboxes under "Sell filters".  If they are checked: does that mean those things WILL be automatically sold or WILL NOT be automatically sold?  I am not sure now which it means, and since it's not working I can't tell from context.

- The "Max Item Level: slider.  In the addon screenshot, there is one sliding marker.  On my screen I have two.  I don't know what that means.  One I can move, and one I can't.  Is the fixed one just there to indicate my level as information?  And the sliding one the actual setting for the filter?  Also, does it mean that it will sell everything up to that set level?  Or sell everything over that set level?

Since these are a bunch of variables, I've tried multiple combinations of slider positions and checked boxes and it still isn't working, but I also see that this depends on the Mog It addon, and maybe THAT is what is causing the problems. I dunno and can't work it out myself :(

I will take a screen shot and send it now, just a sec.

**Comment by goodwin88** [comment]
![nope01](https://user-images.githubusercontent.com/25039338/96279697-0605dc80-0fa5-11eb-916c-ba0911a36e71.jpg)
![nope02](https://user-images.githubusercontent.com/25039338/96279694-056d4600-0fa5-11eb-918e-d0b306c8926e.jpg)

First image shows me at a vendor. No checked boxes.  I have in my bag a cloth item that I can't use/learn (Hunter character).
Second image is same vendor. I checked "can't learn" and still item doesn't show up.  I also moved the slider lower to see if that does anything. You can see there are two markers on the slider bar.  One is fixed and I can't budge it.

**Comment by elvador** [comment]
You're running v7.2.0-1 - please install v9.0.1-1: 
https://www.curseforge.com/wow/addons/transmogcleanup/files/3082354

**Comment by goodwin88** [comment]
I thought I had done this.  Dunno what happened.  It is all fixed now, but had to uninstall both Can I Mog It and TransmogCleanup and then Scan and Repair the WoW install from the BattleNet client before reinstalling Can I Mog It and TransmogCleanup.

But now it does work, thank you!

**Comment by elvador** [comment]
Probably just your addon manager messing up - no worries.

Glad it's working now!
